project_id: "674258"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /pages/**/*.en.mdx
    translation: /pages/**/%file_name%.%two_letters_code%.mdx
    "translation_replace": {
      ".en": ""
    }
