project_id: "674258"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /pages/**/*.en.*
    translation: /pages/**/%file_name%.%two_letters_code%.%file_extension%
    "translation_replace": { ".en": "" }
